examples/book/
├── indoctrinate-structure.json    <- Structure definition for a book
├── frontmatter/
│   ├── Foreward.md
│   └── Fish-Clipart.png
├── chapters/
│   ├── 01/000-Fish.md
│   ├── 02/000-FreshwaterFish.md
│   ├── 02/Salmon.md
│   ├── 03/000-SaltwaterFish.md
│   ├── 04/000-FishThatWorkInBoth.md
│   ├── 05/000-FishAsFood.md
│   └── 06/000-FishAsFriends.md
├── README.md
└── Vocabulary.md
