examples/data_model/
├── indoctrinate.json
├── Platform.md
└── model/
    ├── MeadowModel-Extended.json
    ├── entity/
    │   ├── animals/
    │   │   ├── Author.md
    │   │   └── Cat.md
    │   └── clinics/
    │       ├── Book.md
    │       └── Vet.md
    └── entity_abstractions/
        └── animals.md
